### ISSUE TITLE
Bug in func (set *Set) Size() uint64 

### ISSUE THREAD

**Issue by tfgordon** [mediocregopher/seq#1]
func (set *Set) Size() uint64

returns 1 greater than the size of the set.

**Comment by mediocregopher** [comment]
Hey tom! Thanks for opening the issue. Could you provide a code sample which causes the problem that you're seeing? All my [test cases](https://github.com/mediocregopher/seq/blob/master/hashset_test.go#L128) seem to be passing, so the bug you're seeing must be fairly subtle.

**Comment by tfgordon** [comment]
Sure, no problem.  I've attached my source file, including my workaround 
(the "size") function.  I hope this will help.  I don't have time just 
now to create a small example, but could later if needed.

Tom

**Comment by mediocregopher** [comment]
github doesn't allow for attaching actual files, I think any files you attach through email are simply thrown out =/ could you upload to a gist and link that?

**Comment by tfgordon** [comment]
Hi Brian,

OK. I will take care of this when I get home. I an on the train.

By the way, what I really need are subset and set equality functions. I am using the size function only as a means towards implementing these myself.  But I am not happy with the efficiency of my  implementations and wonder if you could make use of  implementation details of your library to implement them more efficiently.

Tom

**Comment by mediocregopher** [comment]
Hmm wow, apparently I didn't implement an `Equals` method. That's silly of me. I'll get on that tonight or tomorrow if I can.

As a hack in the meantime you could (I think) use `SymDifference` on two sets and check if the result is of size 0, and that would basically be the same as Equal. Or maybe you're already doing that.

I would not necessarily expect super speeds out of this implementation, there's definitely a lot of areas for improvements. I kinda made it as an experiment but I've never used it for a project yet so I haven't felt its pain points. I'd definitely be interested in more feedback on how you find using it and if there's anything else you'd like to see improved.

**Comment by tfgordon** [comment]
Below is my code.  If this works for you, could the problem be with my custom hash function, when trying to implement the Setable interface?  Thanks for your help.

func (s1 seq.Set) subset(s2 seq.Set) bool {
	if s1.Size() <= 0 {
		return true
	}
	if s1.Size() > s2.Size() {
		return false
	}
	f, r, ok := s1.FirstRest()
	for ok {
		_, member := L2.inArgs.GetVal(f)
		if !member {
			return false
		}
		f, r, ok = r.FirstRest()
	}
	return true
}

func (s1 seq.Set) equalSets (s2 seq.Set) bool {
	if s2.Size() != s2.Size() {
		return false
	}
	S := s1.SymDifference(s2)
	if S.Size() == 0 {
		return true
	}
	return false
}

**Comment by tfgordon** [comment]
Oops.  Forgot to use Markdown, so the indendation of the code was lost.  Sccond try:


```go
func (s1 seq.Set) subset(s2 seq.Set) bool {
	if s1.Size() <= 0 {
		return true
	}
	if s1.Size() > s2.Size() {
		return false
	}
	f, r, ok := s1.FirstRest()
	for ok {
		_, member := L2.inArgs.GetVal(f)
		if !member {
			return false
		}
		f, r, ok = r.FirstRest()
	}
	return true
}

func (s1 seq.Set) EqualSets (s2 seq.Set) bool {
	if s2.Size() != s2.Size() {
		return false
	}
	S := s1.SymDifference(s2)
	if S.Size() == 0 {
		return true
	}
	return false
}
```

**Comment by tfgordon** [comment]
A couple of examples illustrating the problem, produced by adding some fmt.Printf statements to my program:

```
S=#{ a13 a14 a1 a8 a18 a4 a11 a16 a3 a9 a15 a0 a7 a12 a17 a5 a10 a19 a2 }#
S.Size()=20
S=#{ a6 a13 a14 a1 a8 a18 a4 a11 a16 a3 a9 a15 a0 a7 a12 a17 a5 a10 a19 a2 }#
S.Size()=21
```

**Comment by mediocregopher** [comment]
In your subset function there is a line with `L2.inArgs.GetVal(f)`, which confused me because I don't see L2 defined anywhere. Is this referencing some other part of the code?

In any case, I was not able to reproduce the size error just with `NewSet("a13", "a14", "a1", "a8", "a18", "a4", "a11", "a16", "a3", "a9", "a15", "a0", "a7", "a12", "a17", "a5", "a10", "a19", "a2")`, perhaps the bug depends on the order the values are inserted? Would it be possible to get a minimal test case which shows this happening? I'm having trouble reproducing it.

I don't think your custom Hash function would cause this problem. That should really only effect whether or not two items collide when inserting, but no matter what `Size()` and `String()` should agree, which they clearly don't.

**Comment by tfgordon** [comment]
OK.  I was able to develop a minimal test  case showing the problems:

```go
package main

import(
	"fmt"
	"github.com/mediocregopher/seq"
)

func main(){	
	s2 := seq.NewSet()
	fmt.Printf("s2.Size() == %v\n", s2.Size())
	fmt.Printf("s2.Size()-1 == %v\n", s2.Size()-1)
	s2, _ = s2.SetVal("b")
	fmt.Printf("s2.Size() = = %v\n", s2.Size())	
}
```
produces this output:

```
s2.Size() == 0
s2.Size()-1 == 18446744073709551615
s2.Size() = = 2
```

Hope this helps.

**Comment by mediocregopher** [comment]
Thanks tom! I'll check that out and see what I can come up with.

**Comment by mediocregopher** [comment]
Fix is live in master (b780fd3). Let me know if that works for you. I'll be adding an Equal method later tonight as well.

**Comment by tfgordon** [comment]
Great!  Many thanks for the quick bug fix.  I really appreciate it.  Keep up the good work.  Go really need a good library for persistent, immutable collections and yours has a lot of promise.

**Comment by mediocregopher** [comment]
Thanks for the kind words :P Latest master also includes the implementation of the `Equal` method on all the concrete data structures, which should help you along. I also made sure that embedding different Seq types within each other is possible and interacts with `Equal` the way you'd expect. Let me know if you find any other bugs or have any other suggestions, and thanks again for submitting the issue :)

**Comment by mediocregopher** [comment]
Also, meant to mention this earlier, but a possibly more concise definition of subset could possible be:

```go
// Returns whether s1 is a subset of s2
func SubSet(s1, s2 *seq.Set) bool {
    return s2.Difference(s1).Size() == 0
}
```

**Comment by tfgordon** [comment]
Sounds good. Does this include embedding sets within sets?

**Comment by mediocregopher** [comment]
It does
