### ISSUE TITLE
seq.NewSet() returns nil

### ISSUE THREAD

**Issue by tfgordon** [mediocregopher/seq#2]
instead of an empty set.

**Comment by tfgordon** [comment]
I'm not sure that returning nil is the actual problem.  The symptom is that seq.NewSet().Size()-1 returns a large positive integer:

```go
package main

import(
	"fmt"
	"github.com/mediocregopher/seq"
)

func main(){	
	fmt.Printf("%v\n", seq.NewSet().Size()-1)
}
```

**Comment by tfgordon** [comment]
Presumably because .Size() returns an unsigned integer.

**Comment by mediocregopher** [comment]
right. `nil` is a valid value for Set, it's just a Set with no items. The problem is you're subtracting 1 from 0 in an unsigned integer, so it overflows and goes back to a high number. if you wrap the Size() call in `int()` or `int64()` you'll get the behavior you want.
